---

##url for access= http://localhost/cgi-bin/smokeping.cgi

- name: "smokeping: Include prerequisites"
  package:
    name: smokeping
    state: present

- name: "smokeping: templates config files, and generate-Targets2-script"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items: "{{ smokeping_templates }}"
  notify:
  - restart smokeping

- name: "Cron: Ensure that the target2 is up to date, 4 times a day."
  cron:
    name: "Ensure that the target2 is up to date"
    minute: "1"
    hour: "*/6"
    user: root
    job: "{{ observium_path }}/scripts/generate-smokeping.php > {{smokeping_config_dir}}/Targets2 && service smokeping restart"
    cron_file: ansible_observium-smokeping

- name: "smokeping: Controlling pathname  for target2"
  lineinfile:
   path: "{{ item.path }}"
   regexp: "{{ item.regxp }}"
   line: "{{ item.line }}"
   backup: yes
  with_items: "{{ smokeping_regxp }}"
  notify:
   - restart smokeping

- name: "smokeping: directory for rrd"
  file:
    path: "{{ smokeping_datadir }}"
    state: directory
    owner: "{{ observium_user }}"
    group: "{{ apache_group }}"
    mode: 0774


- name: "smokeping: Controlling generate-smokeping for compactebily"
  lineinfile:
   path: "{{ observium_path }}/scripts/generate-smokeping.php"
   regexp: 'echo\(\"probe = FPing\"'
   insertbefore: 'echo\(\"host = \"'
   line: '  echo("probe = FPing" . rand(1,4) . PHP_EOL);'
   backup: yes

- name: enable and start smokeping
  service:
    name: smokeping
    enabled: yes
    state: started
