---
- name: template rrdcached service unit, RedHat
  template: >-
    src=rrdcached.service.j2
    dest=/etc/systemd/system/rrdcached.service
    owner=root
    group=root
    mode=0644
  when: ansible_os_family == "RedHat"

- name: template rrdcached service unit, Debian
  template: >-
    src=rrdcached.debian.j2
    dest=/etc/default/rrdcached
    owner=root
    group=root
    mode=0644
  when: ansible_os_family == "Debian"
  notify:
   - restart rrdcached


- name: enable and start rrdcached
  service:
    name=rrdcached
    enabled=yes
    state=started
