---
- name: install epel repository
  yum:
   name: epel-release
   state: installed


- name: install prerequisites
  yum:
   name: "{{ item }}"
   state: installed
   register: apt_yum
  with_items: "{{ observium_packages }}"
